---
- name: Create CSR for certificate
  openssl_csr:
    path: "{{ acme_csr_path }}"
    privatekey_path: "{{ acme_private_key_path }}"
    email_address: "{{ acme_domain.email_address }}"
    country_name: "{{ acme_domain.country | default(omit) }}"
    state_or_province_name: "{{ acme_domain.state_or_province | default(omit) }}"
    locality_name: "{{ acme_domain.locality | default(omit) }}"
    organization_name: "{{ acme_domain.organization | default(omit) }}"
    organizational_unit_name: "{{ acme_domain.organizational_unit | default(omit) }}"
    common_name: "{{ acme_domain.common_name | default(omit) }}"
    subject_alt_name: "DNS:{{ acme_domain.subject_alt_name | join(',DNS:') }}"
  when:
    - acme_domain.subject_alt_name.top_level is undefined and acme_domain.subject_alt_name.second_level is undefined
    - '"dns-01" in acme_provider_path'
  become: true

- name: Create CSR for certificate
  openssl_csr:
    path: "{{ acme_csr_path }}"
    privatekey_path: "{{ acme_private_key_path }}"
    email_address: "{{ acme_domain.email_address }}"
    country_name: "{{ acme_domain.country | default(omit) }}"
    state_or_province_name: "{{ acme_domain.state_or_province | default(omit) }}"
    locality_name: "{{ acme_domain.locality | default(omit) }}"
    organization_name: "{{ acme_domain.organization | default(omit) }}"
    organizational_unit_name: "{{ acme_domain.organizational_unit | default(omit) }}"
    common_name: "{{ acme_domain.common_name | default(omit) }}"
    subject_alt_name: "DNS:{{ (acme_domain.subject_alt_name.top_level | default([])) | union(acme_domain.subject_alt_name.second_level | default([])) | join(',DNS:') }}"
  when:
    - acme_domain.subject_alt_name.top_level is defined or acme_domain.subject_alt_name.second_level is defined
    - '"dns-01" in acme_provider_path'
  become: true

- name: Create CSR for certificate
  openssl_csr:
    path: "{{ acme_csr_path }}"
    privatekey_path: "{{ acme_private_key_path }}"
    email_address: "{{ acme_domain.email_address }}"
    country_name: "{{ acme_domain.country | default(omit) }}"
    state_or_province_name: "{{ acme_domain.state_or_province | default(omit) }}"
    locality_name: "{{ acme_domain.locality | default(omit) }}"
    organization_name: "{{ acme_domain.organization | default(omit) }}"
    organizational_unit_name: "{{ acme_domain.organizational_unit | default(omit) }}"
    common_name: "{{ acme_domain.common_name | default(omit) }}"
    subject_alt_name: "DNS:{{ acme_domain.subject_alt_name | join(',DNS:') }}"
  when:
    - '"http-01" in acme_provider_path'
  become: true
